### ISSUE TITLE
Case 5 mistransliteration

### ISSUE THREAD

**Issue by LouieCFerre** [ScarletStudy/DGS1-3DS-Release#109]
In case 5 after "Bailif" arrived with blood test results, Juror 6 says: "I give piroshki to a little boy and he ran away"
The correct transliteration from russian would be **pirozhki** (пирожки).

**Comment by Wendy-Youngbag** [comment]
Done some research on this and it looks to me (as far as I can tell) that they are just alternate spellings of the same thing (for example: pirozhki is correct, but then over time the spelling changed into a more "English-friendly" version). Since the dude himself is Russian though, I would probably lean more towards the proper transliteration, so I'll go ahead and change that.
