### ISSUE TITLE
Mistranslation on Ep 1

### ISSUE THREAD

**Issue by YoraeYuri** [ScarletStudy/DGS1-3DS-Release#110]
Hi! Upon starting the game I noticed that "Defense" in Defense Attorney is misspelled as Defence.

Please change Defence for Defense.

Also, I noticed in a screenshot a character called "Rola", I have a hunch that this character name could possibly be "Lola" instead of Rola.

Also "Rola" means dick in brazillian portuguese.

**Comment by wabberz** [comment]
- **defence** is the correct spelling in British English: https://dictionary.cambridge.org/dictionary/english/defence
- There is no way to distinguish between R and L in Japanese, since they are the same sound. We chose "Rola" because this preserves the pun of her husbands and her name combined.
- It's a funny/unfortunate (depending on where you stand) coincidence that there is a double meaning in your native language, but this is translation is in British English, not Portuguese. Preserving the pun is more important.
