### ISSUE TITLE
Case 2: Minor text oddities

### ISSUE THREAD

**Issue by AdmiralCurtiss** [ScarletStudy/DGS1-3DS-Release#81]
In order of appearance:

---

![2019-04-27_18-53-28 130_top](https://user-images.githubusercontent.com/4522237/56865902-988e7680-69d3-11e9-9b2d-92237dca3a49.png)

That "A!" at the start looks weird, you usually don't encounter that in English writing. I'd expect an "Ah!" or "Oh!" or similar.

---

![2019-04-27_21-20-59 767_top](https://user-images.githubusercontent.com/4522237/56865918-bbb92600-69d3-11e9-889e-1e0820500149.png)

Extra space between the opening brace and the first letter.

---

![2019-04-28_11-51-14 003_top](https://user-images.githubusercontent.com/4522237/56865924-cecbf600-69d3-11e9-9c9f-e4272bb20eed.png)

There seems to be a missing word in the last sentence from Hosonaga. Perhaps a 'the' in front of 'events'?

---

![2019-04-28_12-00-29 410_bot](https://user-images.githubusercontent.com/4522237/56865935-f1f6a580-69d3-11e9-8956-5511602cc774.png)

The evidence description refers to the polishing substance as 'boot polish', but in dialogue it's always referred to as 'shoe polish'.

![2019-04-28_12-02-24 670_top](https://user-images.githubusercontent.com/4522237/56865940-105ca100-69d4-11e9-9b29-094a10f959fa.png)
![2019-04-28_12-02-57 948_top](https://user-images.githubusercontent.com/4522237/56865942-1488be80-69d4-11e9-9329-9ec250598ac4.png)

I'd suggest matching those.

**Comment by alessiocali** [comment]
I would add, when Nikomina refers to herself as a "Snow-white angel" Ryunosuke makes a comment about the fact that she managed to come up with that phrase despite her "shaky English". Up to that point it has been implied that Ryunosuke & co do not speak English (like in case 1 when Jezail speaks), and therefore they must be speaking Japanese (or that has been my interpretation up to that point)

![Screenshot](https://user-images.githubusercontent.com/7502952/56976415-2e143c80-6b73-11e9-916b-8bab53de03dd.png)

**Comment by keksdee** [comment]
Sorry for taking so long to get back on this. 

1. The "A!" was a typo, seems to be fixed already; either from a previous issue or an informal report. Fixed, thanks.

2. Same deal, it looks like. Fixed, thanks.

3. I kinda feel like it sounds right if you read it a certain way, but it hardly matters. Fixed to add "the," thanks.

4. Changed the evidence description to "shoe polish." Fixed, thanks.

5. Jezail mentions "Queen's English" at one point, which refers to [Received Pronunciation](https://en.wikipedia.org/wiki/Received_Pronunciation), though it's apparently more commonly known as King's English. It's like "stereotypical posh English," so that's why some of what she says is incomprehensible even to English-major Ryuu.
